[package]
name = "zote"
version = "0.1.0"
edition = "2021"

[features]
ast-interpreter = []

[dependencies]
clap = { version = "4.1", features = ["derive"] }
parser = { path = "parser"}
ast_interpreter = { path = "ast_interpreter" }
vm = { path = "vm" }